script:
#############################
# Select correct heater and timer 
#############################
  hotwater_boost_mode:
    sequence:
      - service: timer.start
        data_template:
          entity_id: timer.boost
          duration: >
            {% if is_state('input_boolean.heater_timer1_running', 'on') %}
              00:{{states('input_number.heater_boost_schedule1') | int}}
            {% elif is_state('input_boolean.heater_timer2_running', 'on') %}
              00:{{states('input_number.heater_boost_schedule2') | int}}
            {% else %}
              00:{{states('input_number.heater_boost') | int}} 
            {% endif %} 
      - service: switch.turn_on
        data_template:
          entity_id: >
            {% if is_state('input_select.boost', 'Electric Heater') %}
              switch.immersion
            {% elif is_state('input_select.boost', 'Central Heating') %}
              switch.ch_hotwater
            {% else %}
              switch.ch_hotwater
            {% endif %}
      #=== Don't continue if performance mode not selected
      - condition: template
        value_template: >
          {{ is_state('input_select.boost', 'Performance') }}  
      - wait_template: "{{ states('sensor.pressureswitch_ds18b20_temperature') | int > 40 }}"
      - service: switch.turn_on
        entity_id: switch.immersion

automation:
#############################
# HotWater Switches/Boost sync (not in performance mode)
#############################
  - alias: HotWater Switches/Boost sync
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: >-
          {% if is_state('input_select.boost', 'Electric Heater') %}
             {{is_state('switch.immersion','on') }}
          {% elif is_state('input_select.boost', 'Central Heating') %}
             {{is_state('switch.ch_hotwater','on') }}             
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.boost
        state: 'off' 
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.boost
        
#############################
# Boost Start
#############################
  - alias: Boost Start
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boost
        from: 'off'
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.hotwater_boost_mode
            
#############################
# Boost Cancel
#############################
  - alias: Boost Cancel
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.boost
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: switch.immersion
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: switch.ch_hotwater
        from: 'on'
        to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.boost
      - service: input_boolean.turn_off
        data:
          entity_id:
            - input_boolean.boost
            - input_boolean.heater_timer1_running
            - input_boolean.heater_timer2_running
      - service: switch.turn_off
        data:
          entity_id:
            - switch.immersion
            - switch.ch_hotwater 
      - service: script.turn_off
        entity_id: script.hotwater_boost_mode

#############################
# Boost End
#############################
  - alias: Boost End
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.boost
    action:
      - service: input_boolean.turn_off
        data:
          entity_id:
            - input_boolean.boost
            - input_boolean.heater_timer1_running
            - input_boolean.heater_timer2_running
      - service: switch.turn_off
        data:
          entity_id:
            - switch.immersion
            - switch.ch_hotwater 
#############################
# Boost schedule 1
#############################
  - alias: Boost schedule 1
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: >-
          {% if is_state('input_boolean.heater1_weekdays', 'on')  and is_state('sensor.heating_day_today_timer1', 'True') %}
             {{states('sensor.time') == (state_attr('input_datetime.start_heater1', 'timestamp') | int | timestamp_custom('%H:%M', false)) }}
          {% elif not is_state('input_boolean.heater1_weekdays', 'on') %}
             {{states('sensor.time') == (state_attr('input_datetime.start_heater1', 'timestamp') | int | timestamp_custom('%H:%M', false)) }}
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.heater_timer1
        state: 'on'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id:
            - input_boolean.boost
            - input_boolean.heater_timer1_running

#############################
# Boost schedule 2
#############################
  - alias: Boost schedule 2
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: >-
          {% if is_state('input_boolean.heater2_weekdays', 'on')  and is_state('sensor.heating_day_today_timer2', 'True') %}
             {{states('sensor.time') == (state_attr('input_datetime.start_heater2', 'timestamp') | int | timestamp_custom('%H:%M', false)) }}
          {% elif not is_state('input_boolean.heater2_weekdays', 'on') %}
             {{states('sensor.time') == (state_attr('input_datetime.start_heater2', 'timestamp') | int | timestamp_custom('%H:%M', false)) }}
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.heater_timer2
        state: 'on'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id:
            - input_boolean.boost
            - input_boolean.heater_timer2_running
            
#############################
# clear/select days selection heater timer 1
#############################
  - alias: clear days selection heater timer 1
    trigger:
      - platform: state
        entity_id: input_boolean.heater1_deselect_all_days
      - platform: state
        entity_id: input_boolean.heater1_select_all_days
    action:
      - service_template: > 
          {% if trigger.entity_id == 'input_boolean.heater1_deselect_all_days' %}
            input_boolean.turn_off
          {% elif trigger.entity_id == 'input_boolean.heater1_select_all_days' %}
            input_boolean.turn_on
          {% endif %}
        entity_id:
          - input_boolean.heater1_monday
          - input_boolean.heater1_tuesday
          - input_boolean.heater1_wednesday
          - input_boolean.heater1_thursday
          - input_boolean.heater1_friday
          - input_boolean.heater1_saturday
          - input_boolean.heater1_sunday            

#############################
# clear/select days selection heater timer 2
#############################
  - alias: clear days selection heater timer 2
    trigger:
      - platform: state
        entity_id: input_boolean.heater2_deselect_all_days
      - platform: state
        entity_id: input_boolean.heater2_select_all_days
    action:
      - service_template: > 
          {% if trigger.entity_id == 'input_boolean.heater2_deselect_all_days' %}
            input_boolean.turn_off
          {% elif trigger.entity_id == 'input_boolean.heater2_select_all_days' %}
            input_boolean.turn_on
          {% endif %}
        entity_id:
          - input_boolean.heater2_monday
          - input_boolean.heater2_tuesday
          - input_boolean.heater2_wednesday
          - input_boolean.heater2_thursday
          - input_boolean.heater2_friday
          - input_boolean.heater2_saturday
          - input_boolean.heater2_sunday            
            
            
            
            
