climate:
  - platform: mqtt
    name: "Living Room AC"
    availability_topic: "tele/tasmota_AD9FA1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    current_temperature_topic: "tele/tasmota_AD9FA1/SENSOR"
    current_temperature_template: "{{ value_json.MiElHVAC.Temperature }}"
    precision: 1.0
    temperature_state_topic: "tele/tasmota_AD9FA1/HVACSETTINGS"
    temperature_state_template: "{{ value_json.Temp }}"
    temperature_unit: 'C'
    temp_step: 1
    min_temp: 16
    max_temp: 31
    temperature_command_topic: "cmnd/tasmota_AD9FA1/HVACSetTemp"
    mode_state_topic: "tele/tasmota_AD9FA1/HVACSETTINGS"
    mode_state_template: "{{ value_json.HAMode }}"
    modes:
      - "off"
      - "auto"
      - "heat"
      - "dry"
      - "cool"
      - "fan_only"
    mode_command_topic: "cmnd/tasmota_AD9FA1/HVACSetHAMode"
    action_topic: "tele/tasmota_AD9FA1/HVACSETTINGS"
    action_template: "{{ value_json.HAMode|regex_replace(find='auto', replace='idle', ignorecase=False)|regex_replace(find='heat', replace='heating', ignorecase=False)|regex_replace(find='cool', replace='cooling', ignorecase=False)|regex_replace(find='dry', replace='drying', ignorecase=False)|regex_replace(find='fan_only', replace='fan', ignorecase=False) }}"
    swing_mode_command_topic: "cmnd/tasmota_AD9FA1/HVACSetSwingV"
    swing_mode_state_topic: "tele/tasmota_AD9FA1/HVACSETTINGS"
    swing_mode_state_template: "{{ value_json.SwingV }}"
    swing_modes:
      - "auto"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "swing"
    fan_mode_state_topic: "tele/tasmota_AD9FA1/HVACSETTINGS"
    fan_mode_state_template: "{{ value_json.FanSpeed }}"
    fan_modes:
      - "auto"
      - "1"
      - "2"
      - "3" 
      - "4"
      
    fan_mode_command_topic: "cmnd/tasmota_AD9FA1/HVACSetFanSpeed"

  - platform: mqtt
    name: "Master Bedroom AC"
    availability_topic: "tele/tasmota_553B31/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    current_temperature_topic: "tele/tasmota_553B31/SENSOR"
    current_temperature_template: "{{ value_json.MiElHVAC.Temperature }}"
    precision: 1.0
    temperature_state_topic: "tele/tasmota_553B31/HVACSETTINGS"
    temperature_state_template: "{{ value_json.Temp }}"
    temperature_unit: 'C'
    temp_step: 1
    min_temp: 16
    max_temp: 31
    temperature_command_topic: "cmnd/tasmota_553B31/HVACSetTemp"
    mode_state_topic: "tele/tasmota_553B31/HVACSETTINGS"
    mode_state_template: "{{ value_json.HAMode }}"
    modes:
      - "off"
      - "auto"
      - "heat"
      - "dry"
      - "cool"
      - "fan_only"
    mode_command_topic: "cmnd/tasmota_553B31/HVACSetHAMode"
    action_topic: "tele/tasmota_553B31/HVACSETTINGS"
    action_template: "{{ value_json.HAMode|regex_replace(find='auto', replace='idle', ignorecase=False)|regex_replace(find='heat', replace='heating', ignorecase=False)|regex_replace(find='cool', replace='cooling', ignorecase=False)|regex_replace(find='dry', replace='drying', ignorecase=False)|regex_replace(find='fan_only', replace='fan', ignorecase=False) }}"
    swing_mode_command_topic: "cmnd/tasmota_553B31/HVACSetSwingV"
    swing_mode_state_topic: "tele/tasmota_553B31/HVACSETTINGS"
    swing_mode_state_template: "{{ value_json.SwingV }}"
    swing_modes:
      - "auto"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "swing"
    fan_mode_state_topic: "tele/tasmota_553B31/HVACSETTINGS"
    fan_mode_state_template: "{{ value_json.FanSpeed }}"
    fan_modes:
      - "auto"
      - "1"
      - "2"
      - "3"
      - "4"
    fan_mode_command_topic: "cmnd/tasmota_553B31/HVACSetFanSpeed"       
      
input_select:
  living_ac_widevane:
    name: WideVane
    options:
       -  "swing"
       -  "LL"
       -  "L"
       -  "C"
       -  "R"
       -  "RR"   
       -  "split"       
    icon: mdi:target

automation:
- alias: "Set Living AC Widevane Selector"
  trigger:
    platform: mqtt
    topic: "tele/tasmota_AD9FA1/HVACSETTINGS"
  action:
    service: input_select.select_option
    target:
      entity_id: input_select.living_ac_widevane
    data:
      option: "{{ trigger.payload_json.SwingH }}"
  mode: restart
- alias: "Set Living AC Widevane"
  trigger:
    platform: state
    entity_id: input_select.living_ac_widevane
  action:
    service: mqtt.publish
    data:
      topic: "cmnd/tasmota_AD9FA1/HVACSetSwingH"
      retain: false
      payload: "{{ states('input_select.living_ac_widevane') }}"
      
